environment:
  nodejs_version: '10'

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn ci:pipelines

build: off
deploy: off

cache:
  - node_modules -> yarn.lock
  - "%LOCALAPPDATA%\\Yarn"
